spring:
  profiles:
    active: mysql,kafka,common # switch to 'oracle' as needed

logging:
  level:
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info  # or "*"
  endpoint:
    health:
      show-details: always    # optional - shows extra info like DB, disk, etc.

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true

server:
  port: 9090
