name: Spring Boot CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout source
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      # Grant permissions for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build and run tests
      - name: Build with Gradle
        run: ./gradlew build --no-daemon --info --stacktrace

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: test-reports
            path: |
              build/reports/tests/test
              build/test-results/test

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
            name: app-jar
            path: build/libs/*.jar
